# -*- coding: utf-8 -*-
"""Rupak2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XmpD6yNt1o0c74_2bmTME-HlHybWaS2o
"""

num1=input("Enter the integer")
num2=input("Enter the another integer")
print(num1,type(num1),id(num1))
print(num2,type(num2),id(num2))

x=input("Enter a value")
y=input("Enter another value")
z=x+y
print("Result is",z)

num1=int(input("Enter an integer"))
num2=int(input("Enter another integer"))
print(num1,type(num1),id(num1))
print(num2,type(num2),id(num2))
total=num1+num2
print("so",num1,"+",num2,"=",total)

print("so",str(num1),"+",str(num2),"=",str(total))
x="Rupak "
y="Saha"
print(x+y)

print("so {}+{}={}".format(num1,num2,total)) #place holder
print("So {0}+ {1}={2}".format(num1,num2,total)) #index place holder
print("So {fnum}+ {snum}= {result}".format(fnum=num1,snum=num2,result=total))
print("So {fnum}+ {snum}= {result}".format(snum=num2,result=total,fnum=num1))
print("So %d+ %d =%d"%(num1,num2,total))
print("So %f+ %f =%f"%(num1,num2,total))
print("So %8d+ %8.2f =%d"%(num1,num2,total))
print("So %6d+ %6.2f =%d"%(num1,num2,total))
print(f"so {num1}+{num2}={total}") #f means smart formatting

#String slicing and indexing
mystr=input("Enetr a string")
print(len(mystr),type(mystr),id(mystr))

s="Calcutta University"
print(len(s),type(s),id(s))
print(s[3],s[-2],s[1:3])
print(s[2:10])
print(s[-4:])
print(s[:-4])
print(s[9::-2])

x="cAlCuTtA uNiVeRsItY"
print(x.upper())
print(x.lower())
print(x.swapcase())
print(x.capitalize())
print(x.title())

a="Charity begins at Home"
print(a.find("ity"))

x=input("Enter your name")
a=len(x)
print(a)

def lengthstring(x):
  return(len(x))
#main()
a=input("Enter")
b=lengthstring(a)
print("Length is ",b)

x=input("Enter name:")
for i in range(len(x)):
  print(x[i],end=", ")

def vowcnt(str):
  count=0
  for i in range(len(str)):
    if(str[i]=='A'or str[i]=='E' or str[i]=='I' or str[i]=='O' or str[i]=='U'):
      count=count+1
  return(count)
#main()
a=input("Enter a String")
b=vowcnt(a)
print("No. of Vowels are ",b)

def initial(str):
  src=" "+str
  tgt=""
  for i in range(len(src)):
    if(src[i]==" "):
      tgt=tgt+src[i+1]+"."
  return(tgt)

#main()
a=input("Enter Name")
b=initial(a)
print(b)

def initial(str):
  src=" "+str
  tgt=""
  for i in range(len(src)):
    if(src[i]==" "):
      tgt=tgt+src[i+1]+"."
  return(tgt)
#main()
a=input("Enter Name")
b=initial(a)
print(b)
print(len(a))
for i in range (len(a)-1,-1,-1):
  if(a[i]==" "):
    break
print(i)

x="Sourav Ranjan Das"
tgt=""
for i in range (len(x)-1,-1,-1):
  if(x[i]==" "):
    break
print(i)
for k in range (i,len(x)):
  tgt=tgt+x[k]
print(tgt)

def reverse(str):
  tgt=""
  for i in range(len(str)-1,-1,-1):
    tgt=tgt+str[i]
  if(tgt==str):
    return(True)
  else:
    return(False)

#main()
a=input("Enter a word")
if(reverse(a)==True):
  print("Palindrome")
else:
  print("Not Palindrome")

def chkpalin(str):
  tgt=""
  for i in range(len(str)-1,-1,-1):
    tgt=tgt+str[i]
  if(tgt==str):
    return(True)
  else:
    return(False)

#main()
line=("mom and dad are not at home")
modline=line+" "
sentence=""
flag=0
for j in range (len(modline)):
    if(modline[j]==" "):
      b=chkpalin(sentence)
      if(b==True):
        print(sentence)
        flag=1
      sentence=""
    else:
      sentence=sentence+modline[j]
if(flag==0):
  print("Not a palindrome number present in a sentence")
else:
  print("A palindrome number present in a sentence ")