# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ooqp3bzMA7c8DftZdg70DRONRBT__n8c
"""

x=int(input("Enter a number"))
y=int(input("Enter another number"))
z=x/y
print("Result is ",z)
print("End of program")
a=56
b=98
c=(a+b)

try:
    num1 = int(input("Please enter the first number: "))
    num2 = int(input("Please enter the second number: "))
    result = num1 / num2
    print(num1," / ",num2," = ",result)
except ZeroDivisionError as zde:
    print (" Division By ZERO is Illegal...!!!")
    print ("ZeroDivisionError: Error Type:", type(zde))
    print ("ZeroDivisionError: Error Message:", zde)

print("End of the program...")

try:
    num1 = int(input("Please enter the first number: "))
    num2 = int(input("Please enter the second number: "))
    result = num1 / num2
    print (f"So {num1} / {num2} = {result}...")
except ValueError as ve:
    print ("ValueError: Invalid literal")
    print ("ValueError: Error Type:", type(ve))
    print ("ValueError: Error Message:", ve)
    print("ValueError: Enter an integer value...!!!")

except ZeroDivisionError as zde:
    print (zde)

while(True):
  try:
    num1 = int(input("Please enter the first number: "))
    num2 = int(input("Please enter the second number: "))
    result = num1 / num2
    print (f"So {num1} / {num2} = {result}...")
  except Exception as e:
    print (": Invalid literal")
    print ("Exception: Error Type:", type(e))
    print ("Exception: Error Message:", e)

  except ZeroDivisionError as zde:
    print ("ZeroDivisionError: Division By ZERO is Illegal...!!!")
    print ("ZeroDivisionError: Error Type:", type(zde))
    print ("ZeroDivisionError: Error Message:", zde)
    print("ZeroDivisionError: Division By ZERO is Illegal...!!!")

  except ValueError as ve:
    print ("ValueError: Invalid literal")
    print ("ValueError: Error Type:", type(ve))
    print ("ValueError: Error Message:", ve)
    print("ValueError: Enter an integer value...!!!")
  except Exception as e:
    print (": Invalid literal")
    print ("Exception: Error Type:", type(e))
    print ("Exception: Error Message:", e)
  else:
    break
  finally:
    print("abc")

i=0
while(i<5):
  print("xyz")
  i=i+1
  if(i==2):
    continue
else:
  print("O.K.")

